aws:
  access_key: YOUR_AWS_ACCESS_KEY
  secret_key: YOUR_AWS_SECRET_KEY
  bucket_name: YOUR_AWS_BUCKET_NAME

gcs:
  project: YOUR_GCS_PROJECT_ID
  bucket_name: YOUR_GCS_BUCKET_NAME
  credentials: path/to/your/credentials.json

file_types:
  s3: ["jpg", "png", "svg", "webp", "mp3", "mp4", "mpeg4", "wmv", "3gp", "webm"]
  gcs: ["doc", "docx", "csv", "pdf"]
